# Generated by Django 2.0.1 on 2018-01-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_move_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='status',
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(default='F', max_length=1),
        ),
    ]
